# docker-compose.yml

version: '3.8'
services:

  postgres:
    container_name: babylon_db
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'

  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ToDoSuperStrongPassword
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres:
  minio_storage:
